import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { db, pool, checkoutInventory, checkoutOrders } from "@workspace/db";
import { eq, sql } from "drizzle-orm";
import { createLivestock, updateLivestock, archiveLivestock, ownerInventory, ownerOrderAction, ownerAnalytics } from "../src/lib/admin";
import { createSandboxOrder, readPrivateOrder } from "../src/lib/checkout";

test("protected admin engine: stock, prices, bank idempotency and anonymous reporting", { skip: process.env.ADMIN_TEST_DB !== "true" }, async () => {
  process.env.NODE_ENV = "development";
  process.env.CHECKOUT_SANDBOX_ENABLED = "true";
  process.env.CHECKOUT_LIVE_ENABLED = "false";
  process.env.MCF_SANDBOX_PUBLIC_URL = "https://admin-tests.example.com";
  process.env.SESSION_SECRET = "isolated-bank-test-session-key-not-for-production";
  await db.execute(sql.raw(await readFile(new URL("../../../supabase/migrations/202610030003_admin_bank.sql", import.meta.url), "utf8")));
  const orderIds: string[] = [];
  const sessions = [randomUUID(), randomUUID()];
  let id: number | undefined;
  const input = { name: "QA temporary animal", price: 275, stock: 3, category: "highland-cows", description: "Test fixture, removed after verification", images: ["/family-assets/fghjk.jpg"] };
  const buyer = { name: "QA fixture", email: "admin-check@example.invalid", phone: "0000000000" };
  const conflict = (promise: Promise<unknown>) => assert.rejects(promise, (e: any) => e.statusCode === 409);
  try {
    const created = await createLivestock(input);
    id = created.id;
    assert.equal(created.stock, 3);
    assert.ok(created.slug.endsWith(String(id)));
    const changed = await updateLivestock(id, { ...input, price: 300, active: true, version: created.version, expectedStock: 3 });
    assert.equal(changed.price, 300);
    const request = { buyer, lines: [{ id, qty: 1 }], idempotencyKey: randomUUID(), paymentMethod: "bank" as const };
    const bank = await createSandboxOrder(request);
    orderIds.push(bank.order.id);
    assert.equal(bank.order.paymentMethod, "bank");
    assert.equal(bank.order.status, "pending");
    assert.equal(bank.order.total, 300);
    assert.match(bank.order.bankEmailUrl!, /^mailto:salesminicattlefarm@gmail.com\?/);
    assert.equal((await createSandboxOrder(request)).order.id, bank.order.id);
    await conflict(createSandboxOrder({ ...request, buyer: { ...buyer, name: "Different request" } }));
    assert.equal((await ownerInventory()).find(p => p.id === id)!.available, 3);
    await assert.rejects(readPrivateOrder(bank.order.id, "0".repeat(64)), (e: any) => e.statusCode === 404);
    assert.equal((await readPrivateOrder(bank.order.id, bank.accessToken)).id, bank.order.id);
    await conflict(ownerOrderAction(bank.order.id, "fulfill"));
    const [paid, repeated] = await Promise.all([ownerOrderAction(bank.order.id, "confirm_bank"), ownerOrderAction(bank.order.id, "confirm_bank")]);
    assert.equal(paid.status, "paid");
    assert.equal(repeated.paidAt, paid.paidAt);
    assert.equal((await ownerInventory()).find(p => p.id === id)!.available, 2);
    await conflict(ownerOrderAction(bank.order.id, "cancel_bank"));
    await conflict(updateLivestock(id, { ...input, price: 400, active: true, version: changed.version, expectedStock: 3 }));
    const lowered = await updateLivestock(id, { ...input, price: 250, stock: 2, active: true, version: changed.version, expectedStock: 2 });
    assert.equal(lowered.price, 250);
    assert.equal((await readPrivateOrder(bank.order.id, bank.accessToken)).totalCents, 30000);
    const heldId = randomUUID();
    orderIds.push(heldId);
    await db.transaction(async tx => {
      await tx.update(checkoutInventory).set({ available: 1 }).where(eq(checkoutInventory.id, id!));
      await tx.insert(checkoutOrders).values({ id: heldId, idempotencyKey: randomUUID(), fingerprint: "fixture", accessHash: "fixture", buyer, lines: [{ id: id!, name: input.name, qty: 1, unitPrice: 250 }], totalCents: 25000, status: "pending", expiresAt: new Date(Date.now()+60000) });
    });
    const held = (await ownerInventory()).find(p => p.id === id)!;
    assert.equal(held.reserved, 1);
    assert.equal(held.stock, 2);
    await conflict(updateLivestock(id, { ...input, stock: 0, active: true, version: lowered.version, expectedStock: 2 }));
    await conflict(archiveLivestock(id, lowered.version));
    await conflict(ownerOrderAction(heldId, "confirm_bank"));
    await db.transaction(async tx => {
      await tx.update(checkoutOrders).set({ status: "failed", released: true }).where(eq(checkoutOrders.id, heldId));
      await tx.update(checkoutInventory).set({ available: 2 }).where(eq(checkoutInventory.id, id!));
    });
    const tooMany = await createSandboxOrder({ ...request, lines: [{ id, qty: 3 }], idempotencyKey: randomUUID() });
    orderIds.push(tooMany.order.id);
    await conflict(ownerOrderAction(tooMany.order.id, "confirm_bank"));
    assert.equal((await ownerInventory()).find(p => p.id === id)!.available, 2);
    await ownerOrderAction(tooMany.order.id, "cancel_bank");
    assert.equal((await ownerInventory()).find(p => p.id === id)!.available, 2);
    const fulfilled = await ownerOrderAction(bank.order.id, "fulfill");
    assert.ok(fulfilled.fulfilledAt);
    assert.equal((await ownerOrderAction(bank.order.id, "fulfill")).fulfilledAt, fulfilled.fulfilledAt);
    const archived = await archiveLivestock(id, lowered.version);
    assert.equal(archived.active, false);
    await conflict(createSandboxOrder({ ...request, idempotencyKey: randomUUID() }));
    const parts = new Intl.DateTimeFormat("en", { timeZone: "Africa/Lagos", year: "numeric", month: "2-digit" }).formatToParts(new Date());
    const month = `${parts.find(p => p.type === "year")!.value}-${parts.find(p => p.type === "month")!.value}`;
    const baseline = await ownerAnalytics("daily", month);
    for (let i=0; i<3; i++) await db.execute(sql`insert into sandbox_checkout_visits(event_id,session_id,path) values(${randomUUID()}::uuid,${sessions[i===2?1:0]}::uuid,'/shop')`);
    const daily = await ownerAnalytics("daily", month);
    assert.equal(daily.totals.revenue, 0, "Sandbox paid orders never count as real earnings");
    assert.equal(daily.totals.pageViews, baseline.totals.pageViews+3);
    assert.equal(daily.totals.visitors, baseline.totals.visitors+2);
    assert.equal((await ownerAnalytics("monthly", undefined, month.slice(0,4))).buckets.length, 12);
    assert.equal((await ownerAnalytics("daily", "2026-02")).buckets.length, 28);
    await assert.rejects(ownerAnalytics("daily", "2026-13"));
  } finally {
    for (const orderId of orderIds) await db.delete(checkoutOrders).where(eq(checkoutOrders.id, orderId));
    if (id) await db.delete(checkoutInventory).where(eq(checkoutInventory.id, id));
    for (const session of sessions) await db.execute(sql`delete from sandbox_checkout_visits where session_id=${session}::uuid`);
    await pool.end();
  }
});